const SUCCESS = 200;
const CREATED_SUCCESS = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;

module.exports = {
  SUCCESS,
  CREATED_SUCCESS,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  SERVER_ERROR,
};
